os:
  - linux
  - osx
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 6
  - 7
  - 8
  - 9
  - 10
  - node
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "npm run build"
install:
  - npm install
script:
  - npm run test
